#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "Yunyi's blog"
# Short bio or description (displayed in the header)
description: "I am a Ph.D. student, majoring in Biostatistics, minoring in Computer Science, interested in statistics, deep learning, machine learning, longitudinal, irregularly sampling"
# Pursuing Ph.D. degree is an exiciting advanture to embrace big challenges, a great oppotunity to understand the beauty of uncertainty, a secret view to see how tiny we are, but how big we can make by the power of knowlege."

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/Yunyi-learner/Yunyi-s-Homepage/main/images/avatar.png
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://raw.githubusercontent.com/Yunyi-learner/Yunyi-s-Homepage/main/images/animal-dog.ico

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: Home
    url: /
  - name: Biography
    url: /about
  - name: Archive
    url: /archive
  - name: Tag
    url: /tags

# Pagination
paginate: 8

excerpt_separator: <!-- more -->

# Includes an icon in the footer for each username you enter
footer-links:
  #weibo: frommidworld #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<username>
  dribbble:
  zhihu: jolie-8-28
  email: lliyuny@iu.edu
  facebook:
  flickr:
  github: Yunyi-learner 
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin: yunyi-li-94832aa9
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  #twitter: frommidworld
  youtube:

# Text under the icons in footer
footer-text: Copyright (c) 2021 Yunyi Li

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # fromendworld

# Gitalk
gitalk:
  clientID: ed74c19c7bd8a7e1de25
  clientSecret: ddc1e1def9442c6c2e81cb1dcae64f8673123377
  repo: Yunyi-learner.github.io
  owner: Yunyi

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://yunyi-learner.github.io/Yunyi-s-Homepage/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: 

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

